services:
  admin-back:
    build: 
      dockerfile: Dockerfile
      context: .
      tags:
        - admin-back
    networks:
      admin-net: 
        ipv4_address: 172.16.0.2
    ports: 
      - ${PORT}:${PORT}
    restart: always
    environment:
      PORT: ${PORT}
      # Escribir secreto para encriptar (cadena de caracteres alfanumericos de 256 caracteres)
      SECRET: ${SECRET}
      BDD_HOST: 172.16.0.3
      BDD_USER: root
      # Escribir contraseña de la base de datos
      BDD_PASSWORD: ${DB_PASSWORD}
      BDD_DATABASE: faco_luz
      BDD_PORT: ${DB_PORT}
      BDD_TIMEOUT: ${DB_TIMEOUT}
      BDD_CONECTION_LIMITS: ${DB_CONNECTION_LIMITS}

  admin-db:
    build:
      context: .
      dockerfile: Dockerfile-db
      tags: 
        - admin-db
    networks:
      admin-net: 
        ipv4_address: 172.16.0.3
    restart: always
    environment:
      # A condinuacion escribir la contraseña de la base de datos
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes: 
      - ${API_VOLUME}:/var/lib/mysql

networks:
  admin-net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
